name: Run Simulator
on: [workflow_dispatch]  # Mahdollistaa manuaalisen käynnistyksen
jobs:
  run-simulator:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - run: python simulator.py
