name: Run Simulator
on: [workflow_dispatch]  # Mahdollistaa manuaalisen käynnistyksen
jobs:
  run-simulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run simulator
        run: |
          echo "Simulator starting..."
          # Lisää komennot, jotka käynnistävät simulaattorin
